fix(iOS): stuttering back arrow animation when using headerLargeTitle
software-mansion/react-native-screens pull request #2014
Opened 2024-01-17 17:03 UTC by dylancom

## Description
When navigating to a screen that has a large header title and the back title hidden, the back arrow animation bugs (kind of bounces in / stuttery animation).
I noticed that when setting the title to a string, it animates normally.
I found that using a space instead of a complete empty string, the title of the previous screen animates nicely, instead of disappearing instantly.

2024-01-18 14:15 UTC, tboba commented
Hi @dylancom, thanks for creating this PR! 🥳 
Hm, that's strange 🤔 do you know on which iPhone and which iOS does this back button stutter? I'm seeing this behavior the first time!

2024-01-18 14:20 UTC, dylancom commented
You're welcome!
I have tested this on an iPhone 15 Pro, iOS 17.0.

2024-01-18 14:34 UTC, tboba commented
@dylancom Yeah, something's definitely wrong there 🤔 
Do you know if previously in RNScreens this bug was also happening for you?

2024-01-18 14:36 UTC, dylancom commented
@tboba I have no idea, I haven't been using headerLargeTitle in this way before.

2024-01-19 08:48 UTC, dylancom commented
@tboba anything more needed to see this merged?

2024-01-20 14:59 UTC, focux commented
I'm experiencing this same issue. I'm using an iPhone 15 Pro with iOS 17.2 and react-native-screens `^3.27.0`

2024-01-20 18:08 UTC, tboba commented
@dylancom not at the moment, thanks! Currently I'm struggling with fixing main branch, as it's quite broken, but I'll take a look on that in upcoming days 🙌
@focux thanks for confirming!

2024-01-22 10:50 UTC, tboba commented
@dylancom I've just tested this PR and it looks like this change fixes the bug with the title, but unfortunately it breaks the animation of appearing title after pressing back button 😢

Without the change:

https://github.com/software-mansion/react-native-screens/assets/23281839/ecbe7224-c2d3-479a-bcc9-396a166a09d2

With the change (notice that right now the title is being scaled instead of appearing from the side):

https://github.com/software-mansion/react-native-screens/assets/23281839/2242cf4b-5941-493c-9234-52bdda0d721d

Do you know if there's any other solution for fixing that back button item?

2024-01-22 10:55 UTC, dylancom commented
If you remove the space and just use an empty string, it doesn't scale.
`[backBarButtonItem setTitle:@""];`

2024-01-22 11:02 UTC, tboba commented
@dylancom Yeah, actually I was trying to set the title of the button to an empty string and it breaks the animation - hence I see that you've added an empty space to the title. Sorry for misleading you!

2024-01-22 11:10 UTC, tboba requested changes

2024-01-22 11:10 UTC, tboba commented on ios/RNSScreenStackHeaderConfig.mm
> +    [backBarButtonItem setTitle:@" "];
Unfortunately, this change still breaks how the hint for the previous screens looks like. With the changed title, it is being set to empty field, which is unacceptable. Can we think about the better approach or "hack" the hints in other way?

https://github.com/software-mansion/react-native-screens/assets/23281839/5cd8f6c1-0039-4c45-b5de-7ac9c194de8c

2024-01-23 10:26 UTC, tboba commented on ios/RNSScreenStackHeaderConfig.mm
> +    [backBarButtonItem setTitle:@" "];
@dylancom thanks! I've tried some methods mentioned in StackOverflow, but unfortunately setting the text color to `Clear` doesn't fix that bug. Also, I've tried to create a custom menu that will contain the title of the previous screen, but somehow iOS doesn't replace it after calling `setMenu` (I also don't want to steer the menu manually). Hence I'm afraid I won't merge this for now - I don't want to sacrifice one functionality for another, but of course you can patch screens with this change on your own.

2024-01-24 18:51 UTC, tboba commented
@dylancom as I said in the subcomment, because of the bug that comes with this change, I won't merge this PR for now (I also can't find any other solution for fixing this issue). If you have any suggestion how this can be fixed, don't hesitate to re-open this PR! Otherwise, can you fill a new issue with the bug described here? You can link this PR to know the additional context of our attempts. Thanks!

2024-01-24 18:51 UTC, closed without merging