chore(TVOS): rebuild TVOSExample app with RN 0.74.1
software-mansion/react-native-screens pull request #2155
Opened 2024-05-22 12:55 UTC by alduzy

## Description

PR rebuilding TVOSExample from scratch with RN 0.74.1.

## Changes

- rebuild TVOSExample app with latest RN version

## Test code and steps to reproduce

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Updated documentation: 
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/guides/GUIDE_FOR_LIBRARY_AUTHORS.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/native-stack/README.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/src/types.tsx
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/src/native-stack/types.tsx
- [ ] Ensured that CI passes

2024-05-27 06:15 UTC, kkafar reviewed
I guess we need to make CI work before we proceed here. It does somehow build on main, wo we should be able to make it work here too (as well as running it locally).

2024-06-07 19:19 UTC, tboba requested changes
Great job! 🥳

2024-06-07 19:19 UTC, tboba commented on TVOSExample/ios/Podfile
> +# end
Should this part be commented out?

2024-06-07 19:19 UTC, tboba commented on TVOSExample/src/BottomTabsExample.tsx
Can we grab the examples from `apps` directory?

2024-06-10 07:31 UTC, alduzy commented on TVOSExample/src/BottomTabsExample.tsx
I created a separate PR for that: https://github.com/software-mansion/react-native-screens/pull/2173

2024-06-10 07:36 UTC, alduzy commented on TVOSExample/android/app/src/main/res/drawable/tv_banner.png
Yes 😄 https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.74.0/packages/react-native/template/android/app/src/main/res/drawable/tv_banner.png

2024-06-10 07:37 UTC, alduzy commented on TVOSExample/android/app/build.gradle
> +    // hermesFlags = ["-O", "-output-source-map"]
Yes, by default at least: https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.74.0/packages/react-native/template/android/app/build.gradle

2024-06-10 07:57 UTC, alduzy commented on .github/workflows/tv-os-build-test.yml
> +          xcode-version: latest-stable
https://github.com/software-mansion/react-native-screens/pull/2155/commits/b56ee31761ef41f0f136e59802404bccfe4f800f

2024-06-10 09:18 UTC, alduzy commented on .github/workflows/tv-os-build-test.yml
> +        run: npx react-native run-ios --scheme="TVOSExample-tvOS" --simulator="Apple TV"
Unfortunately I could not make the expo script to work properly in CI

2024-06-10 09:21 UTC, tboba approved these changes
Okay then 👍

2024-06-10 11:40 UTC, merged