Implement blurEffect for new arch
software-mansion/react-native-screens pull request #2207
Opened 2024-06-24 05:29 UTC by janicduplessis

## Description

Implements blurEffect header config for new arch.

## Changes

 I kept this super simple and used string for codegen so we can simply reuse the RCTConvert implementation.

## Test code and steps to reproduce

Tested that header blur now works in an app with new arch enabled.

## Checklist

- [ ] Included code example that can be used to test this change
- [x] Updated TS types
- [x] Updated documentation: 
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/guides/GUIDE_FOR_LIBRARY_AUTHORS.md
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/native-stack/README.md
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/src/types.tsx
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/src/native-stack/types.tsx
- [x] Ensured that CI passes

2024-06-25 09:30 UTC, tboba requested changes
Hi, thanks for creating this PR! I left a comment about the way how we're defining that prop in a Spec.

2024-06-25 09:30 UTC, tboba commented on src/fabric/ScreenStackHeaderConfigNativeComponent.ts
> +  blurEffect?: string;
I don't know if I'm fond of setting blurEffect as a string. In our `types.tsx`, we're using a special [type](https://github.com/software-mansion/react-native-screens/blob/main/src/types.tsx#L42) for defining every possible string that could be a blurEffect. I'm concerned if there could be a situation, where invalid `blurEffect` entered here could just bring a crash on iOS. Some day ago, there was [that](https://github.com/software-mansion/react-native-screens/pull/1751) PR that was also adding a support for `blurEffect` on Fabric. Sadly, it has been abandoned, but maybe you could try to actually enter the type to the Spec and check if it'll just work the same as with `string`?

2024-06-26 01:16 UTC, janicduplessis commented
@tboba Thanks for having a look. I will verify how incorrect values are handled. I liked the simplicity of this approach since it can use the same conversion code as the old arch, but I can also implement it using an enum, it will just require an extra function to convert from the codegen enum to the uikit one.

2024-06-26 01:17 UTC, janicduplessis commented
Looks like there is also an android build issue I will need to fix.

2024-06-28 21:52 UTC, janicduplessis commented
@tboba Update to use enum and fixed android build!

2024-08-02 21:13 UTC, janicduplessis commented
@tboba Friendly ping on this :)

2024-08-05 09:41 UTC, tboba commented
Hey hey @janicduplessis, yeah I'll try to check that today 👍 Thanks for the nudge :D

2024-08-05 14:40 UTC, tboba approved these changes
Everything looks good to me! 🫡 
Let's proceed when builds will pass 👍

2024-08-05 15:29 UTC, merged