Monorepo Support: Use node resolver for react native location
software-mansion/react-native-screens pull request #2337
Opened 2024-09-06 20:42 UTC by morganick

- **Using node resolver to find react native package for better monorepo support**
- **yarn prepare does not exist in react-navigation**

## Description

## Changes

## Test code and steps to reproduce

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Updated documentation: 
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/guides/GUIDE_FOR_LIBRARY_AUTHORS.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/native-stack/README.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/src/types.tsx
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/src/native-stack/types.tsx
- [ ] Ensured that CI passes

2024-09-06 20:50 UTC, morganick commented on android/build.gradle
> +        if (reactNativePackage.exists()) {
Inspect with:
```
println reactNativePackage.parentFile
```

You'll then see this output in the terminal when you run `yarn android` again.

2024-09-09 19:41 UTC, morganick commented
I'm able to run the same command locally that is failing in CI. I've also dropped back to node 18.20.4 locally to see if that made a difference. Everything continues to build normally.

It appears that for some reason `projectDir` is `null` on CI. I'd like to try running this with `rootDir` as it continues to work locally with that. `rootDir` resolves to the `android` directory in each of the `Example` and `FabricExample` projects.

2024-09-25 14:16 UTC, kkafar requested changes
Hello, I've finally found time to test this, thank you for the contribution, we will surely merge this!

First, however, I need to articulate my confusion regarding differences between old and new approach. 

Honestly I do not understand, why does the current main code even work. In context of `react-native-screens`, `$projectDir` in "regular client react-native application" resolves to `App/node_modules/react-native-screens/android`, thus `"$projectDir/../node_modules/react-native/android"` resolves to `App/node_modules/react-native-screens/node_modules/react-native/android` => This look like we've been pointing to wrong react-native module over the last couple of years!? What's even more baffling is that when you inspect `App/node_modules/react-native-screens/node_modules/react-native` it surely does not contain `android` subdirectory... I'm sure there are mechanisms I'm just now aware now as of right now, but that's just crazy ;D 

Okay, so looking at the solution you propose I think we're fine on the first part, and the fallback to "new-old" approach with `rootDir` instead of `projectDir` also does make more sense than starting point old approach, at least for now. 

I've tested this on:

1. newly created standard react native app & it seems to be working,
2. our examples in the library repository - they work just fine.

Only remark that my purist brain brings up is that maybe we should first look for "standard" application structure and if it fails, just then try to handle other cases with fallback code. Basically swap the cases around, so that we do not run whole search algorithm if it is not needed.

I'm thinking this through right now & I believe such swap won't break any behaviour you expect in monorepo, hence I'll allow myself to change it. **Let me know, if I'm in wrong** and the order is important.

There is one more thing to do: revert changes to `guides/CONTRIBUTING.md` file. You are right - these guidelines are wrong, however your suggestion is also wrong, despite the fact that `yarn prepare` commands exists in our repo :D I'll fix this in separate PR. 

Since I can't push to your fork I'll close this PR, cherry-pick your changes and open a new one.

2024-09-25 14:47 UTC, closed without merging

2024-09-25 14:55 UTC, kkafar commented
Surrogate PR: https://github.com/software-mansion/react-native-screens/pull/2352