Allow the fontweight for the title to be customized
software-mansion/react-native-screens pull request #706
Opened 2020-11-12 17:37 UTC by dylancom

## Description

Currently you can customize the fontFamily and fontSize but not the fontWeight (of the header title).
This PR let's you also change the fontWeight of the header title.

2020-11-17 10:34 UTC, WoLewicki commented
Thanks for your contribution! 
1. In the PR template, there are all the places where the change/addition of a property should be added. It looks like you've missed the READMEs of `native-stack` and `createNativeStackNavigator`.
2. Can you add this change to Android too? It should be rather simple. You can check here: https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java#L236 and extend the `if` to check for both `weight` and `FontFamily`, only `FontFamily` (current), only `weight`.

If you need any help, please comment here.

2020-12-04 11:01 UTC, dylancom commented
@WoLewicki I tried Android but it had no effect, see: https://github.com/facebook/react-native/issues/26193.
Seems that if you want for e.g. a bold font, you need to specify a bold font family.
I updated the READMEs, improved the iOS code and added an example.

2020-12-07 12:33 UTC, WoLewicki requested changes
Looks good! Please apply the changes requested and this should be ready to merge then!

2020-12-07 12:33 UTC, WoLewicki commented on README.md
> +#### `titleFontWeight`
If it is not available on Android, please add the `(iOS only)` in all READMEs and other files with this.

2020-12-07 12:33 UTC, WoLewicki commented on TestsExample/App.js
> +  return <Test706 />;
Please don't change the default test file.

2020-12-07 12:33 UTC, WoLewicki commented on TestsExample/ios/Podfile.lock
> +COCOAPODS: 1.10.0
We shouldn't mix normal changes with such ones in the same PR. Please change it back to what it was.

2020-12-07 12:33 UTC, WoLewicki commented on ios/RNSScreenStackHeaderConfig.h
> +@property (nonatomic, retain) NSString *titleFontWeight;
I think we could add the same but for `largeTitle`, the changes should look pretty similar to the normal title.

2020-12-07 13:39 UTC, dylancom commented
@WoLewicki I applied the requested changes.

2020-12-07 14:05 UTC, WoLewicki requested changes
Some minor tweaks.

2020-12-07 14:05 UTC, WoLewicki commented on ios/RNSScreenStackHeaderConfig.m
> +      if (config.titleFontFamily || config.titleFontWeight) {
```suggestion
      if (family || weight) {
```

2020-12-07 14:05 UTC, WoLewicki commented on ios/RNSScreenStackHeaderConfig.m
> +        if (config.largeTitleFontFamily || config.largeTitleFontWeight) {
```suggestion
        if (largeFamily || largeWeight) {
```

2020-12-07 14:05 UTC, WoLewicki commented on ios/RNSScreenStackHeaderConfig.m
> +    if (config.titleFontFamily || config.titleFontWeight) {
same as above

2020-12-07 14:05 UTC, WoLewicki commented on ios/RNSScreenStackHeaderConfig.m
> +    if (config.largeTitleFontFamily || config.largeTitleFontWeight) {
same as above

2020-12-07 14:05 UTC, WoLewicki commented on src/index.d.ts
> +     */
```suggestion
    /**
     * @host (iOS only)
     * @description Customize the weight of the font to be used for the title.
     */
```

2020-12-07 14:05 UTC, WoLewicki commented on src/native-stack/types.tsx
> +    fontWeight?: string;
Please add this prop to the description above with a note (iOS only)

2020-12-07 14:05 UTC, WoLewicki commented on src/native-stack/types.tsx
> +export type NativeStackNavigatorProps = DefaultNavigatorOptions<NativeStackNavigationOptions> &
Please revert it

2020-12-07 14:30 UTC, dylancom commented
@WoLewicki Tweaked it.

2020-12-07 16:14 UTC, WoLewicki commented on src/native-stack/types.tsx
> +   * - fontWeight
```suggestion
   * - fontWeight (iOS only)
```

2020-12-07 16:21 UTC, WoLewicki commented
Ok it looks like it is ready to be merged :tada: Thanks for your contribution!

2020-12-07 16:21 UTC, WoLewicki approved these changes

2020-12-07 16:24 UTC, merged