feat: add option for disabling ios 14 menu
software-mansion/react-native-screens pull request #830
Opened 2021-02-24 11:23 UTC by WoLewicki

## Description

Added an option for disabling back button menu on iOS >= 14 based on https://github.com/wix/react-native-navigation/pull/6874.

## Changes

## Test code and steps to reproduce

## Checklist

- [x] Included code example that can be used to test this change
- [x] Updated TS types
- [x] Updated documentation: 
  - [x] https://github.com/software-mansion/react-native-screens/blob/master/README.md
  - [x] https://github.com/software-mansion/react-native-screens/blob/master/native-stack/README.md
  - [x] https://github.com/software-mansion/react-native-screens/blob/master/createNativeStackNavigator/README.md
  - [x] https://github.com/software-mansion/react-native-screens/blob/master/src/index.d.ts
  - [x] https://github.com/software-mansion/react-native-screens/blob/master/src/native-stack/types.tsx
- [x] Ensured that CI passes

2021-02-25 11:40 UTC, kacperkapusciak approved these changes

2021-05-02 13:17 UTC, ferrannp commented
@WoLewicki any plans to release this? 🙏 .

2021-05-21 09:02 UTC, kacperkapusciak requested changes
Great job on making the back button menu working on v5! 🎉  There's a small issue on v4

2021-05-21 09:02 UTC, kacperkapusciak commented on src/createNativeStackNavigator.tsx
> +        newRoutes.splice(backRouteIndex, dismissCount > 0 ? dismissCount : 1);
and that's why here even if you pass the correct number of screens to be dismissed it starts at the wrong index (always previous screen)

2021-05-21 09:57 UTC, kacperkapusciak commented on src/createNativeStackNavigator.tsx
> +        newRoutes.splice(backRouteIndex, dismissCount > 0 ? dismissCount : 1);
Fixed in 5e9ebd3

2021-05-21 10:01 UTC, kacperkapusciak approved these changes
LGTM!

2021-05-21 10:59 UTC, merged

2021-06-12 20:13 UTC, nandorojo commented
@WoLewicki Thanks for this PR!

Question – is it possible to use the iOS back button menu with a custom header that I have on my screen?

I'd like to wrap my custom back button here with the menu. Is there an exported component I could do that with? For instance:

```tsx
<BackButtonMenu>
  <MyComponent />
</BackButtonMenu>
```

https://user-images.githubusercontent.com/13172299/121788155-10f72800-cb99-11eb-9681-9972a6ab8a67.mov

2021-06-14 08:31 UTC, WoLewicki commented
Native back button item is a part of `UINavigationItem`, which is connected to `UINavigationBar`, so you cannot use that button without having the native `UINavigationBar` as far as I know. One solution I can think of is to make your own native button with `UIMenu` added to it, which elements would trigger the native navigation action when clicked.

2024-04-22 03:17 UTC, bryanltobing commented
> Native back button item is a part of UINavigationItem, which is connected to UINavigationBar, so you cannot use that button without having the native UINavigationBar as far as I know. One solution I can think of is to make your own native button with UIMenu added to it, which elements would trigger the native navigation action when clicked.

wonder if this is still not possible?